# ==========================================
# Google Cloud Build Configuration (WITH SEED)
# ==========================================
# Cloud Run'a otomatik deploy için + Seed işlemi
# 
# ⚠️ DİKKAT: Bu dosya her deploy'da seed çalıştırır
# Sadece ilk deploy'da kullanın, sonra normal cloudbuild.yaml kullanın

steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/obs-api:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/obs-api:latest'
      - '.'

  # Push the Docker image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/obs-api:$COMMIT_SHA'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/obs-api:latest'

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'obs-api'
      - '--image'
      - 'gcr.io/$PROJECT_ID/obs-api:$COMMIT_SHA'
      - '--region'
      - 'europe-west1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '5000'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '10'
      - '--set-env-vars'
      - 'NODE_ENV=production,FRONTEND_URL=https://obs-frontend-214391529742.europe-west1.run.app'
      - '--set-secrets'
      - 'DB_HOST=DB_HOST:latest,DB_USER=DB_USER:latest,DB_PASSWORD=DB_PASSWORD:latest,DB_NAME=DB_NAME:latest,JWT_SECRET=JWT_SECRET:latest'

  # Seed veritabanı (sadece ilk deploy'da veya gerektiğinde)
  # ⚠️ Bu adım her deploy'da çalışır, ama findOrCreate kullandığı için veriler tekrar oluşturulmaz
  - name: 'gcr.io/$PROJECT_ID/obs-api:latest'
    entrypoint: 'node'
    args: ['src/seeders/seedPart2Data.js']
    env:
      - 'NODE_ENV=production'
    secretEnv: ['DB_HOST', 'DB_USER', 'DB_PASSWORD', 'DB_NAME', 'JWT_SECRET']
    waitFor: ['-']  # Önceki adımların tamamlanmasını bekle

# Store images in Container Registry
images:
  - 'gcr.io/$PROJECT_ID/obs-api:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/obs-api:latest'

# Build timeout
timeout: '1200s'

# Build options
options:
  logging: CLOUD_LOGGING_ONLY

# Secret'ları Cloud Build'e bağla
availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/DB_HOST/versions/latest
      env: 'DB_HOST'
    - versionName: projects/$PROJECT_ID/secrets/DB_USER/versions/latest
      env: 'DB_USER'
    - versionName: projects/$PROJECT_ID/secrets/DB_PASSWORD/versions/latest
      env: 'DB_PASSWORD'
    - versionName: projects/$PROJECT_ID/secrets/DB_NAME/versions/latest
      env: 'DB_NAME'
    - versionName: projects/$PROJECT_ID/secrets/JWT_SECRET/versions/latest
      env: 'JWT_SECRET'

